services:
  web:
    build: ./web
    networks:
      - red
    ports:
      - "8081:80"
    depends_on: 
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: app_db
    volumes:
      - datos_db:/var/lib/mysql
    networks:
      - red
      
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - red
networks:
  red:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
          ip_range: 192.168.20.64/26
volumes:
  datos_db:
